# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: ${PORT:8080}
  servlet:
    # 应用的访问路径
    context-path: /api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.leda: debug
    org.springframework: warn

# Spring配置
spring:
  config:
    import:
      - classpath:wechat.yml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://139.196.146.52:3306/le_da?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:g0IAc7eO2Tz2}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 2MB
      # 设置总上传的文件大小
      max-request-size: 20MB


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.leda.entity
  config-location: classpath:mybatis/mybatis-config.xml

#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 1
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 1
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #逻辑删除配置
#    logic-delete-value: -1
#    logic-not-delete-value: 0
#    #自定义SQL注入器
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    call-setters-on-nulls: true
#    #springboot 项目mybatis plus 设置 jdbcTypeForNull (oracle数据库需配置JdbcType.NULL, 默认是Other)
#    jdbc-type-for-null: 'null'
#    log-impl: org
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: ${SWAGGER_ENABLE:true}


# 项目相关配置
leda:
  domain: ${LEDA_DOMAIN:https://www.kuailedazi.cn}

knife4j:
  enable: ${KNIFE4J_ENABLE:true}
  openapi:
    title: leda
    description: "leda接口文档"
    email: ""
    concat: leda
    version: v4.0
    group:
      test1:
        group-name: leda
        api-rule: package
        api-rule-resources:
          - com.leda
